"""crear tablas usuario cliente prestador_servicio

Revision ID: 5fa6e0cf26d5
Revises: 
Create Date: 2026-09-10 12:07:47.850036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa6e0cf26d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_apellido', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('localidad', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=False)
    op.create_table('prestador_servicio',
    sa.Column('id_prestador', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('departamento', sa.String(), nullable=True),
    sa.Column('prom_calificacion', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_prestador'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_prestador_servicio_id_prestador'), 'prestador_servicio', ['id_prestador'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prestador_servicio_id_prestador'), table_name='prestador_servicio')
    op.drop_table('prestador_servicio')
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
